# Generated by Django 2.2.3 on 2019-07-13 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zomato', '0002_auto_20190713_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='sector',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
