# Generated by Django 2.2.3 on 2019-07-13 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zomato', '0004_remove_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zomato.Menu'),
        ),
    ]
