# Generated by Django 2.2.3 on 2019-07-13 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('zomato', '0005_auto_20190713_0925'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('veg', models.BooleanField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zomato.Dish')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='taggedmenuitem',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='taggedmenuitem',
            name='tag',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='order_id',
            new_name='transaction_id',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='customer',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='ordered_items',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='menu',
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='MenuItem',
        ),
        migrations.DeleteModel(
            name='TaggedMenuItem',
        ),
        migrations.AddField(
            model_name='dish',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zomato.Hotel'),
        ),
    ]
