# Generated by Django 2.2.3 on 2019-07-13 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zomato', '0006_auto_20190713_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='photo',
            field=models.ImageField(null=True, upload_to='hotel_photos'),
        ),
    ]
